### ISSUE TITLE
Any  plan to release a new version?

### ISSUE THREAD

**Issue by kabeor** [ethereum/blake2b-py#13]
Hi, is there any plan to release a new version so blake2b-py can support python 3.10 by https://github.com/ethereum/blake2b-py/pull/10 ?

**Comment by MT-Cash** [comment]
@cburgdorf The current version on PyPI is 0.1.4 : https://pypi.org/project/blake2b-py/
Thats pretty old and a couple of commits are missing: https://github.com/ethereum/blake2b-py/compare/f7dda6ede0b9c006578854f055cefff75acf2ddc...master

Would you mind to create a new release on PyPI?

**Comment by cburgdorf** [comment]
@kclowes I noticed you are already an admin for this project. Would you mind taking over the maintenance? I'm so detached from Python development these days. It looks like #9 would be a good candidate to merge but I think it should be rebased to run against CI first.

**Comment by MT-Cash** [comment]
@cburgdorf If the project currently has no active maintainer and nobody volunteers from within the project, you might want to consider https://github.com/jazzband

**Comment by kclowes** [comment]
@cburgdorf - can you give me pypi privileges? Then I can get a release out, hopefully early next week.

**Comment by cburgdorf** [comment]
Sure, thanks a lot Keri!

**Comment by cburgdorf** [comment]
> @cburgdorf - can you give me pypi privileges? Then I can get a release out, hopefully early next week.

Turns out, I don't have managing privileges on pypi either. I can push releases but can not add other maintainers. @davesque Could you add Keri?

**Comment by kclowes** [comment]
I just got Pypi permissions 🎉  will plan to do a release early next week!

**Comment by MT-Cash** [comment]
@kclowes Is there anything blocking you from making a release? Is there any way you can be supported?

**Comment by kclowes** [comment]
@MT-Cash Thanks for checking :) 0.2.0 is out!
